export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_FAILURE = 'FETCH_QUESTIONS_FAILURE';

export const LOADING_TRUE = 'LOADING_TRUE';
export const LOADING_FALSE = 'LOADING_FALSE';

export const NOTIFY_USER_TRUE = 'NOTIFY_USER_TRUE';
export const NOTIFY_USER_FALSE = 'NOTIFY_USER_FALSE';
